### ISSUE TITLE
Implement HTTP server pseudo-node in Oak Runtime

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#1186]
Similar to the gRPC server pseudo-node, we need an HTTP server pseudo-node to allow external interaction with the Oak application. 
One use case is to expose monitoring APIs: #736, #977

Oak SDK and Oak ABI must be updated to allow using the gRPC server pseudo-node. 

This includes:
- [x] Implementing basic HttpServerNode in the Runtime (#1261)
- [x] APIs in the SDK to use the HttpServerNode (#1338)
- [x] Add TLS support (#1345)
- [x] Add authentication with challenge-based authentication (#1357)
- [ ] Update documentation
- [x] Add an example to showcase the use of HTTP server pseudo-node (#1338, #1370)
- [x] ABI tests (#1334) 
- [ ] Refactoring the common parts between `HttpServerNode` and `GrpcServerNode` into a submodule (#1390)
  - [ ] Generic invocation message for GrpcRequest and HttpRequst: see [comment on #1261](https://github.com/project-oak/oak/pull/1261#discussion_r458603731)
  - [ ] Single shared tokio runtime: #1280 

Other related issues:
- [x] Response headers: #1458
- [x] Idiomatic types in SDK: #1459
- [ ] Switch to HTTP/2: #1481
