### ISSUE TITLE
Runner suggestions

### ISSUE THREAD

**Issue by anghelcovici** [project-oak/oak#1283]
I've been playing a bit with the Runner and I want to brain dump some possible improvements. Not sure if these are already covered by other issues:

- [ ] There is no progress indicator. Getting stuck on a step for 300+ seconds is not great. Can we have a spinning thing? :)
- [x] I didn't have Bazel installed. The error was not clear (`panic occurred: could not spawn command: Os { code: 2, kind: NotFound, message: "No such file or directory" }`) and it has hard to investigate. Maybe improve error messages to show/dump detailed logs when crashing?
    - Error logs seem more helpful now: `panic occurred: could not spawn command: Command { std: "prettier" "--write" "./oak_sign/Cargo.toml", kill_on_drop: false }: No such file or directory (os error 2)`
- [x] On [this run](https://pantheon.corp.google.com/cloud-build/builds/571d674e-ff87-4deb-b7fd-dc6333965e7a;step=4?project=oak-ci), the formatter had an error, but the build continued for 30 minutes. Can we stop things as soon as the error happens? (Issue: https://github.com/project-oak/oak/issues/1291) 
    - [DONE: Behaviour changed in 3ead617fc405d4574beb7c15d31cc0afc7054271]
- [ ] Building Runner takes 3 minutes on my mac and it also require a nightly compiler. Can we prebuild it? Also, do we really need experimental features in a tool?
- [ ] The builds are not deterministic (as in the order is not the same). I've ran this in docker on may machine and in docker on a mac and they proceed in different order. Should we make them deterministic?
- [ ] There is no output by default for the examples. Can we enable the running of examples to show output by default?
- [ ] When building the hello_world example there is no way to exclude the cpp module from being built. This adds quite a lot of time for the first build I did.
- [x] A C++ module for the `hello_world` example is not currently being run (Issue: https://github.com/project-oak/oak/issues/1250, PR: https://github.com/project-oak/oak/pull/1281).
- [x] I had an error in the "build application" step and the runner continued to running the server. Is this intentional?
    - [DONE: It was, but behaviour changed in 3ead617fc405d4574beb7c15d31cc0afc7054271]
- [x] We are not building the Rust client for TIR. Do we support Rust clients in the runner? (Issue: https://github.com/project-oak/oak/issues/1285, PR: https://github.com/project-oak/oak/pull/1287)
- [x] Choose client variants in runner (Issue: https://github.com/project-oak/oak/issues/1294, PR: https://github.com/project-oak/oak/pull/1298).

cc: @benlaurie @tiziano88 @ipetr0v

**Comment by anghelcovici** [comment]
@ipetr0v - the runner seem to build the cpp module, but not run it

**Comment by ipetr0v** [comment]
Updated

**Comment by conradgrobler** [comment]
The output from the node.js Hello World example also does not seem to display even when running with the `--logs` comandline parameter.

**Comment by ipetr0v** [comment]
`runner` could also be non-deterministic, because it uses [WalkDir](https://docs.rs/walkdir/2.3.1/walkdir/) to search for examples.

**Comment by anghelcovici** [comment]
@ipetr0v , I've added this item: On [this run](https://pantheon.corp.google.com/cloud-build/builds/571d674e-ff87-4deb-b7fd-dc6333965e7a;step=4?project=oak-ci), the formatter had an error, but the build continued for 30 minutes. Can we stop things as soon as the error happens?

Did you recently fix something similar?

**Comment by ipetr0v** [comment]
I was adding an error summary in the end: https://github.com/project-oak/oak/pull/1286
Will look into this.
