### ISSUE TITLE
Tracking issue: Policy needs

### ISSUE THREAD

**Issue by seefeldb** [project-oak/oak#1410]
This is a tracking issue for policy requirements, expressed as simplified examples of problems that _might_ be addressable with policies.

Let's use the issues to discuss/link to possible approaches and close them with either an explanation for how to express such a policy (closed) or why we consider it out of scope for a while (wontfix). Alternatively link the issue for a working example.

- [ ] #488 Chat policies
- [ ] #1411 Evolving policies
- [ ] #1412 Evolving policies, two stage processing
- [x] #1413 Aggregation, user's perspective
- [ ] #1414 Aggregation, aggregator's perspective

A couple more complex examples that we need to break down into smaller ones as above:
- [ ] #1422 Identity corner case: Proving a university degree from a now defunct university
