### ISSUE TITLE
Transport-agnostic client library for Oak 

### ISSUE THREAD

**Issue by rbehjati** [project-oak/oak#3066]
We need a generic and transport-agnostic Oak Client library with common functionality for interacting with a trusted Oak runtime by sending and receiving encrypted messages. This library should provide the functionality that is in common between different variants of the client, regardless of the remote attestation flavour that is used for establishing the attested connection. 

Here is a high-level description of the behaviour of an Oak client:
* Get encryption keys and create an encryptor object
* Get evidence about the server (endorsement evidence, and optionally some config) and verify that
* If happy, encrypt and send messages to the server

These three things are in general separate concerns, and our design should allow them to be done separately, by different types.

We need this library for both Rust and Java. The idea is to provide abstractions, and a public API based on that, that the client code (e.g., the Android client) can depend on without having to depend on specific implementations. 

The following is the architecture I propose, and have partly implemented in #3062 (in Java), for the generic client API.  

![Oak Client-library](https://user-images.githubusercontent.com/12942581/179790673-b7fc1eec-f5eb-4729-b210-aac3dd388db9.png)

The following diagram shows the general sequence of events on the client.

![Oak Client-Page-2 drawio](https://user-images.githubusercontent.com/12942581/181240315-2c035ec0-f711-4d0e-8803-d18c71e124b5.png)

1. Regardless of the remote attestation protocol, the client first asks the `EvidenceProvider` for evidence about the server. In a complete implementation, the evidence must contain the remote attestation quote, containing the server's signing public key, and endorsement evidence. 
2. The client verifies the evidence. If the provided evidence is valid (with respect to some _policy_ internal to the client), then the server's signing public key is returned. Otherwise, the connection is dropped. 
3. The client then requests the `EncryptorProvider` for an Encryptor. This requires passing the signing public key of the server to the `EncryptorProvider`. (In the current implementation of the interactive remote attestation protocol the `signingPublicKey` is part of the `ServerIdentity`. This is not a good approach, as this public key that is used for handshake is unverified. A better and more secure practice, as described here, is to first verify the signing public key and only proceed with the handshake if the public key is valid.)
4. The client requests the `RpcClientProvider` for an instance of an `RpcClient` that can be used for sending and receiving messages. 
5. The uses the `RpcClient` to send and receive encrypted messages, and uses the `Encryptor` to encrypt and decrypt messages. 

The following depicts the current Rust-implementation of the interactive remote attestation protocol. It already provides some of the abstractions above (`UnaryClient` below is the same thing as `RpcClient` above). Eventually these two parts should be merged and implemented in both Java and Rust. 

![Oak Functions Rust Client](https://user-images.githubusercontent.com/12942581/179793412-c98df2ff-8162-4df2-8894-8586bd537a0e.png)

**Client Implementations**
Eventually we will have multiple implementations of the `OakClient`. The implementations will most likely mainly differ in the use of the transparent protocol (e.g., HTTP, Unary gRPC, and Streaming gRPC), the remote attestation protocol, and perhaps the API versions for the specification and exchange of evidence. Factory methods will be provided for creating instances of each concrete type, with the choice of the transport and remote attestation protocols and the API versions reflected in the name of the factory method. 

**Implementation Steps**
Since the Java client is used in the Android implementation, the focus of the implementation will be on the Java client. The rust client will be updated afterwards, how ever we should try and keep the implementations in sync. Having a modular design should simplify verifying and maintaining the consistency between the two implementations. 

- [ ] Top-level library for `oak_client`, with subfolders for Java and Rust (this will change if we decide to have top-level folders in the root of the repo for each language; see https://github.com/project-oak/oak/issues/2533#issuecomment-1177833255)
- [ ] Implement endorsement verification logic 
- [ ] Refactor AttestationClient in Java into smaller classes, using the proposed design here. 
   - [ ] Replicate the current implementation of the interactive remote attestation in Rust for Java. Only the client-side part. 
   - [ ] Ensure backward compatibility, until we deprecate the old usage.
   - [ ] Minor changes in existing implementations (e.g., to the encryptor, and the implementation of the Result type)
- [ ] Provide factory methods for instantiating the client. 
- [ ] Implement this for the Rust client.
