### ISSUE TITLE
Rust Oak Runtime

### ISSUE THREAD

**Issue by blaxill** [project-oak/oak#540]
### Rust Oak Runtime dev status

- [x] Rust runtime with passing Wasm tests - #472
- [ ] ~~Remove `std` requirements from remaining dependencies enabling linking in Asylo SGX - #546~~
- [x] Move from an implicit ownership of reference counted points to explicitly runtime owned channels, and track nodes ownership/usage of channels
#633
   - [x] Runtime ownership of Nodes (in #690)
   - [x] Runtime ownership of Channels #646 (in #680 #728)
   - [x] Track channels per node (#768)
- [x] gRPC support
   - [x] gRPC server entrypoint (#695)
   - [x] gRPC server pseudo-node in Rust Oak Runtime (#751)
- [x] Enable running tests
- [x] Enable running examples through the rust runtime (Blocked on gRPC support)
- [ ] Storage node
- [ ] Rough time node (#730)
- [ ] ~~FFI interface to runtime~~
   - [ ] ~~Enable using C++ nodes (#724)~~

### Non-critical path

- [ ] Re-enable relevant sdk tests - #544
- [X] Remove hard links to Wasm modules in tests - #541
- [x] Remove `inner_main` - #542
- [ ] Move grpc_request to oak_runtime - #543

**Comment by daviddrysdale** [comment]
"Add shim to allow using existing C++ nodes" is now also covered by #724 I think.

**Comment by daviddrysdale** [comment]
I think this issue can be closed out now: we're running a Cargo-built Rust Runtime, and remaining bits of missing functionality are covered by other issues:
 - #953: streaming support for gRPC server pseudo-Node
 - #954: streaming support for gRPC client pseudo-Node
 - #1040: re-implement storage functionality in some form
 - #730: re-implement Roughtime functionality
 - #544: re-enable unit test functionality (e.g. fault injection)
 - #543, #1038: rejig test setup for Nodes
