### ISSUE TITLE
Migrate away from Asylo

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/oak#709]
Checklist of sub-tasks needed to remove dependency on Asylo:

- C++ code:
  - [x] Drop use of EKEP in dev server (#701)
  - [x] Encapsulate Asylo logging (#679)
  - [x] Move code to a forked `oak::StatusOr` not `asylo::StatusOr` (#712)
  - [x] Drop `oak/server/asylo/` (#713)
  - [x] Use alternative AEAD functionality for storage (subsumes #517)  (#720)
  - [x] Remove `:host_tests` Bazel targets (#716)
  - [x] Drop use of `enclave.proto` (#731)
  - [x] Get aggregator Docker image working with dev server (#718, #721)
  - [x] Migrate OAK_LOG to use gLog (#732)
  - [x] Drop `com_google_asylo` from WORKSPACE (subsumes #354) (#732)
- Rust code (#711):
   - [x] Move `oak_runtime` crate to use `std` directly 
   - [x] Drop `oak_platform` crate
   - [x] Drop `oak_platform_asylo` crate (subsumes #662)
   - [x] Drop `third_party/rust`
 - Scripts
   - [x] Update to be dev-server only (#713)
   - [x] ~~Remove use of different `--output_base` values for Bazel?~~ (No, needed for parallel Cloudbuild builds)
   - [ ] Make local builds work without Docker (now there's no need for the Asylo toolchain)?
 - Docs
   - [x] Build and install instructions (#735)
   - [x] Concepts and programming guide (#735, #741)
   - [x] Diagrams (#741)
