### ISSUE TITLE
Rust Runtime features for running Oak applications

### ISSUE THREAD

**Issue by ipetr0v** [project-oak/oak#818]
This checklist contains features that must be implemented in the Rust Oak Runtime in order to run Oak applications, viz. existing [example applications](https://github.com/project-oak/oak/tree/master/examples).

- [x] Implement Rust Oak Loader (Issue: https://github.com/project-oak/oak/issues/723, PR: https://github.com/project-oak/oak/pull/749)
- [x] Rust gRPC *server* pseudo-node
    - [x] Implement gRPC *server* pseudo-node (Issue: https://github.com/project-oak/oak/issues/751, PR: https://github.com/project-oak/oak/pull/772)
    - [x] Add TLS support (Issue: https://github.com/project-oak/oak/issues/806, PR: https://github.com/project-oak/oak/issues/806)
        - [x] Add `tonic` as a crate in `cargo-raze` (Issue: https://github.com/project-oak/oak/issues/890, PR: https://github.com/project-oak/oak/pull/891)
    - [x] Refactor pseudo-node creation (Issue: https://github.com/project-oak/oak/issues/982, PR: https://github.com/project-oak/oak/pull/985)
    - [x] Add streaming support (Issue: https://github.com/project-oak/oak/issues/953)
    - [x] Implement unit tests (Issue: https://github.com/project-oak/oak/issues/807, PR: https://github.com/project-oak/oak/pull/1109)
- [x] Rust gRPC *client* pseudo-node
    - [x] Implement Rust gRPC *client* pseudo-node (Issue: https://github.com/project-oak/oak/issues/844, PR: https://github.com/project-oak/oak/pull/909)
    - [x] Add streaming support (Issue: https://github.com/project-oak/oak/issues/954, PR: https://github.com/project-oak/oak/pull/1056)
- [x] Run [examples](https://github.com/project-oak/oak/tree/master/examples) with Rust Oak Loader (Issues: https://github.com/project-oak/oak/issues/725, https://github.com/project-oak/oak/issues/874, PR: https://github.com/project-oak/oak/pull/993)
    - [x] Enable `abitest` additional tests (requires storage pseudo-node and Roughtime pseudo-node)
    - [x] Enable `tensorflow` (requires either Wasm stubs for WASI entrypoints like #529, or remove the need for them #817)
    - [x] Enable C++ examples (Issue: https://github.com/project-oak/oak/issues/1009, PR: https://github.com/project-oak/oak/pull/1019)

**Comment by ipetr0v** [comment]
cc @tiziano88 @daviddrysdale @conradgrobler

**Comment by daviddrysdale** [comment]
I think we can close this out as remaining things are covered by other issues (esp #1040 for storage)?
